# Generated by Django 3.0.7 on 2020-07-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('purchase_date', models.DateField()),
                ('sale_date', models.DateField(blank=True, null=True)),
                (
                    'purchase_price',
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    'purchase_tax',
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    'sale_price',
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    'sale_tax',
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
            ],
        ),
    ]
